### ISSUE TITLE
Outside readings and graph not showing

### ISSUE THREAD

**Issue by ofernander** [tkrofta/signalk-barograph-plugin#1]
Just like the title says, outside readings and graph is not working. Any idea why? Log doesn't give any errors or hints. 

![image](https://github.com/tkrofta/signalk-barograph-plugin/assets/35053416/268adea2-9781-4a45-99d7-d0d0a8cc9086)

**Comment by 0x0f906** [comment]
Resolved

For anyone else having this issue, you need to be explicit with the IP of the influx host and the SignalK host simply putting "localhost" caused the above error.

**Comment by ofernander** [comment]
Resolved

For anyone else having this issue, you need to be explicit with the IP of the influx host and the SignalK host simply putting "localhost" caused the above error.
