### ISSUE TITLE
webapp not updated

### ISSUE THREAD

**Issue by Colug0** [tkrofta/signalk-barograph-plugin#2]
it looks like the plugin is working correctly in the background (no errors in log, all the values under environment.barometer get pushed to signalk) but the web app gets no updates. Any ideas whats going wrong?
<img width="715" alt="image" src="https://github.com/tkrofta/signalk-barograph-plugin/assets/77384058/bb37cdaa-39dd-4066-8a4a-3a1a5ab981a9">

<img width="766" alt="image" src="https://github.com/tkrofta/signalk-barograph-plugin/assets/77384058/fc34e3a1-b34b-42a9-888a-2b026b174228">

**Comment by tkrofta** [comment]
@Colug0 - we've seen this behaviour before when the account logging into SignalK is not equal to the user account specified in the connection string of the plugin configuration: The WebApp is therefore missing authorization to query SignalK/Influx data. Can you please doublecheck your **signalk-barograph** config for the _Connection String (server|username|password)_ setting to be specified as
`http://server-ip:server-port|user|password`

**Note**: you may want to avoid using _localhost_ and rather specify the server by fully qualified domain name or IP.

Let us know here whether or not that re-solves the issue.

**Comment by Colug0** [comment]
I just exchanged the account i creates for the baro plugin withe the account I use to login as admin. Now the plugin works fine. thanks for the help
